#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# Remove immersed-body diagnostics
rm -rf bodiesInfo
mkdir -p bodiesInfo

# ----------------------------------------------------------------- end-of-file
